/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    DateRangePicker: typeof import('./../components/DateRangePicker/index.vue')['default']
    GiCellAvatar: typeof import('./../components/GiCell/GiCellAvatar.vue')['default']
    GiCellGender: typeof import('./../components/GiCell/GiCellGender.vue')['default']
    GiCellStatus: typeof import('./../components/GiCell/GiCellStatus.vue')['default']
    GiCellTag: typeof import('./../components/GiCell/GiCellTag.vue')['default']
    GiCellTags: typeof import('./../components/GiCell/GiCellTags.vue')['default']
    GiCodeView: typeof import('./../components/GiCodeView/index.vue')['default']
    GiDot: typeof import('./../components/GiDot/index.tsx')['default']
    GiFlexibleBox: typeof import('./../components/GiFlexibleBox/index.vue')['default']
    GiFooter: typeof import('./../components/GiFooter/index.vue')['default']
    GiForm: typeof import('./../components/GiForm/src/GiForm.vue')['default']
    GiIconSelector: typeof import('./../components/GiIconSelector/index.vue')['default']
    GiOption: typeof import('./../components/GiOption/index.vue')['default']
    GiOptionItem: typeof import('./../components/GiOptionItem/index.vue')['default']
    GiOverFlowTags: typeof import('./../components/GiOverFlowTags/index.vue')['default']
    GiSvgIcon: typeof import('./../components/GiSvgIcon/index.vue')['default']
    GiTable: typeof import('./../components/GiTable/index.vue')['default']
    GiTag: typeof import('./../components/GiTag/index.tsx')['default']
    GiThemeBtn: typeof import('./../components/GiThemeBtn/index.vue')['default']
    Icon403: typeof import('./../components/icons/Icon403.vue')['default']
    Icon404: typeof import('./../components/icons/Icon404.vue')['default']
    Icon500: typeof import('./../components/icons/Icon500.vue')['default']
    IconBorders: typeof import('./../components/icons/IconBorders.vue')['default']
    IconTableSize: typeof import('./../components/icons/IconTableSize.vue')['default']
    IconTreeAdd: typeof import('./../components/icons/IconTreeAdd.vue')['default']
    IconTreeReduce: typeof import('./../components/icons/IconTreeReduce.vue')['default']
    JsonPretty: typeof import('./../components/JsonPretty/index.vue')['default']
    ParentView: typeof import('./../components/ParentView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextCopy: typeof import('./../components/TextCopy/index.vue')['default']
    Verify: typeof import('./../components/Verify/index.vue')['default']
    VerifyPoints: typeof import('./../components/Verify/Verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./../components/Verify/Verify/VerifySlide.vue')['default']
  }
}
